#ifndef BODYTYPEENUM_H
#define BODYTYPEENUM_H

enum BodyTypeEnum {
	RESET,
	GET_STATUS,
	SAVE_CONFIG,
	SET_PARAMETER,
	GET_PARAMETER,
	START_MEASURE,
	STOP_MEASURE,
	SET_NTP_TIMESTAMP_SEC,
	SET_NTP_TIMESTAMP_FRACSEC
};

#endif // BODYTYPEENUM_H
