#ifndef PARAMETERENUM_H
#define PARAMETERENUM_H

enum ParameterEnum {
	IP_ADDRESS,
	TCP_PORT,
	SUBNET_MASK,
	STANDARD_GATEWAY,
	DATA_OUTPUT_FLAG,
	START_ANGLE,
	END_ANGLE,
	SCAN_FRECUENCY,
	SYNC_ANGLE_OFFSET,
	ANGULAR_RESOLUTION_TYPE,
	ANGLE_TICKS_PER_ROTATION
};

#endif // PARAMETERENUM_H
